/** Auto-sourced B2B companies — REGENERATED by src/jobs/source-b2b.ts (Claude
 *  web-search research). Do not hand-edit; the curated base lives in b2b-data.ts.
 *  Each entry additionally carries `sourced_at` (ISO date) and `source: 'auto'`.
 *  Starts empty; the sourcing job appends fresh finds (deduped against the base). */
import type { B2BCompany } from './b2b-data.ts';

export type SourcedCompany = B2BCompany & { sourced_at?: string; source?: 'auto' };

export const SOURCED: SourcedCompany[] = [
  {
    "name": "Sardine",
    "category": "Fraud & compliance platform",
    "channel": "API",
    "arr": "Series C, fast",
    "customers": "Fintechs, banks, crypto platforms",
    "signal": 78,
    "build": "complex",
    "url": "https://www.sardine.ai",
    "note": "Consolidating fraud+AML+KYC into one API as fintech compliance costs balloon.",
    "features": [
      "Device fingerprinting",
      "Fraud risk scoring",
      "AML transaction monitoring",
      "KYC orchestration"
    ],
    "wedge": "Not a week play: requires real device-intelligence data, ML fraud models, and regulatory integrations that can't be credibly faked in an MVP.",
    "competitors": [
      "Sift",
      "Alloy",
      "Unit21",
      "SEON"
    ],
    "sourced_at": "2026-07-01",
    "source": "auto"
  },
  {
    "name": "Sana",
    "category": "AI knowledge assistant",
    "channel": "Web app",
    "arr": "~$40M ARR est.",
    "customers": "Enterprises, L&D teams",
    "signal": 72,
    "build": "weeks",
    "url": "https://sanalabs.com",
    "note": "Swedish knowledge-AI player pivoting hard into enterprise agents.",
    "features": [
      "Enterprise search",
      "AI agents over company data",
      "Meeting/knowledge capture",
      "Learning management"
    ],
    "wedge": "Week-1 MVP: connect Slack+Google Drive via OAuth, index docs into a vector store, ship a RAG chat UI answering company questions.",
    "competitors": [
      "Glean",
      "Guru",
      "Notion AI",
      "Dust"
    ],
    "sourced_at": "2026-07-01",
    "source": "auto"
  },
  {
    "name": "Fern",
    "category": "API dev tooling",
    "channel": "API",
    "arr": "Seed/Series A, fast",
    "customers": "Dev-tool & API companies",
    "signal": 65,
    "build": "weeks",
    "url": "https://buildwithfern.com",
    "note": "Auto-generating SDKs/docs as every AI company scrambles to ship developer APIs.",
    "features": [
      "SDK generation",
      "API docs generation",
      "OpenAPI tooling",
      "Type-safe client libraries"
    ],
    "wedge": "Week-1 MVP: parse an OpenAPI spec and auto-generate a typed TypeScript/Python SDK plus a hosted docs page.",
    "competitors": [
      "Stainless",
      "Speakeasy",
      "Mintlify",
      "ReadMe"
    ],
    "sourced_at": "2026-07-01",
    "source": "auto"
  },
  {
    "name": "Mintlify",
    "category": "AI documentation platform",
    "channel": "Web app",
    "arr": "Series A, fast",
    "customers": "Dev-tool & SaaS companies",
    "signal": 70,
    "build": "week",
    "url": "https://mintlify.com",
    "note": "Became the default docs stack for AI/dev-tool startups fast.",
    "features": [
      "AI-assisted docs writing",
      "Docs-as-code hosting",
      "API reference pages",
      "AI chat over docs"
    ],
    "wedge": "Week-1 MVP: render Markdown/MDX repos into a hosted docs site with an embedded RAG chatbot over the content.",
    "competitors": [
      "ReadMe",
      "GitBook",
      "Docusaurus",
      "Fern"
    ],
    "sourced_at": "2026-07-01",
    "source": "auto"
  },
  {
    "name": "Parloa",
    "category": "AI contact-center agents",
    "channel": "API",
    "arr": "Series C, fast",
    "customers": "Enterprises with large call centers",
    "signal": 74,
    "build": "complex",
    "url": "https://www.parloa.com",
    "note": "Raised a large round at unicorn valuation for enterprise voice automation.",
    "features": [
      "Voice AI agents",
      "Contact-center automation",
      "Multi-language support",
      "CRM/telephony integrations"
    ],
    "wedge": "Not a week play: real-time voice pipelines, telephony integration, and enterprise CRM connectors require deep infra and reliability engineering.",
    "competitors": [
      "Sierra",
      "Cresta",
      "PolyAI",
      "Decagon"
    ],
    "sourced_at": "2026-07-01",
    "source": "auto"
  },
  {
    "name": "Julius AI",
    "category": "AI data analyst",
    "channel": "Web app",
    "arr": "Seed, fast growth",
    "customers": "Analysts, SMBs, ops teams",
    "signal": 66,
    "build": "week",
    "url": "https://julius.ai",
    "note": "Fast consumer-to-prosumer growth doing conversational data analysis.",
    "features": [
      "Chat with spreadsheets/CSV",
      "Auto chart generation",
      "Statistical analysis",
      "Python code execution"
    ],
    "wedge": "Week-1 MVP: upload CSV, run an LLM that writes+executes Python in a sandbox, and render charts/answers back in chat.",
    "competitors": [
      "ChatGPT Data Analysis",
      "Hex",
      "Rows",
      "Numerous.ai"
    ],
    "sourced_at": "2026-07-01",
    "source": "auto"
  },
  {
    "name": "Braintrust",
    "category": "LLM eval & observability",
    "channel": "API",
    "arr": "Series A, fast",
    "customers": "AI product teams",
    "signal": 71,
    "build": "weeks",
    "url": "https://www.braintrust.dev",
    "note": "Becoming the eval layer teams adopt as they push LLM apps to production.",
    "features": [
      "LLM evals & scoring",
      "Prompt experimentation",
      "Production tracing",
      "Dataset management"
    ],
    "wedge": "Week-1 MVP: log LLM calls via SDK, store prompt/response pairs, and run a simple scoring harness with a diff UI across model versions.",
    "competitors": [
      "LangSmith",
      "Humanloop",
      "Arize",
      "Langfuse"
    ],
    "sourced_at": "2026-07-01",
    "source": "auto"
  }
];
